site_name: BentoBox World
nav:
    - Home: index.md
    - FAQ: BentoBox/wiki/FAQ.md
    - Gamemodes:
        - BSkyBlock: BSkyBlock/wiki/index.md
        - AcidIsland: AcidIsland/wiki/index.md
        - SkyGrid: SkyGrid/wiki/index.md
        - CaveBock: CaveBlock/wiki/index.md
    - Addons:
        - Challenges: Challenges/wiki/index.md
        - Level: Level/wiki/index.md
        - Limits: Limits/wiki/index.md
        - Greenhouses: Greenhouses/wiki/index.md
        - CauldronWitchery: CauldronWitchery/wiki/index.md
        - CheckMeOut: CheckMeOut/index.md
    - "Tutorials – Generic":
        - "Set a BentoBox world as the server's default world": BentoBox/wiki/Set-a-BentoBox-world-as-the-server-default-world.md
    - "Tutorials – API":
        - "Create an Addon": Tutorials/api/addons/Create-an-addon.md
        - "Config API": BentoBox/wiki/Config-API.md
        - "Database API": BentoBox/wiki/Database-API.md
theme:
  name: readthedocs
markdown_extensions:
  - toc:
      permalink: "#"
